quarkus:
  application:
    name: cadastro
  http:
    port: 8083
  devservices:
    enabled: false
  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    username: cadastro
    password: cadastro
    jdbc:
      url: jdbc:postgresql://localhost:5433/cadastro
  testcontainers:
    enabled: false
  hibernate-orm:
    database:
      generation: update
  flyway:
    clean-at-start: true
    migrate-at-start: true
  jaeger:
    service-name: ifood-cadastro
    endpoint: http://localhost:14268/api/traces
    sampler-param: 1
    sampler-type: const

amqp-host: localhost
amqp-port: 5672
amqp-username: artemis
amqp-password: artemis

mp:
  messaging:
    outgoing:
      restaurantes:
        connector: smallrye-amqp
        address: restaurantes

  jwt:
    verify:
      issuer: http://localhost:8081/realms/ifood
      publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsPpG36RUAOrfcOmT1xM9wJ20NjKNto/SRHAEH59unW2/jZVpbdHjSZ31sdC8MLt0PkRWu89yaH5WqQ8II0UwjRVv51zNJRC8IEgnzDYskS794VhyBZ84yc+AGxiEbH8zTP749qjzKGorjX/MR0WibVmr5o9L3+AHcHetWwwVENxNAHycxB3pPVbVy5LBGb5eDzEY1TDf8WvpnS9uTpNEKr6VjE/CpmfnuonJB9BhSniIywo2fpCn8k8wMY6dLgCN5n5XsGd8i1ZovMamv1YIYjeiiTcoqVaq3/mVMKDP2176zj8jC61zUtgHdsvKD9U4F9w40MrQN+eY0FN+knoTIwIDAQAB