quarkus:
  application:
    name: cadastro
  http:
    port: 8083
  devservices:
    enabled: false
  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    username: cadastro
    password: cadastro
    jdbc:
      url: jdbc:postgresql://localhost:5433/cadastro
  testcontainers:
    enabled: false
  hibernate-orm:
    database:
      generation: update
  flyway:
    clean-at-start: true
    migrate-at-start: true
  jaeger:
    service-name: ifood-cadastro
    endpoint: http://localhost:14268/api/traces
    sampler-param: 1
    sampler-type: const

amqp-host: localhost
amqp-port: 5672
amqp-username: artemis
amqp-password: admin

mp:
  messaging:
    outgoing:
      restaurantes:
        connector: smallrye-amqp
        address: restaurantes

  jwt:
    verify:
      issuer: http://localhost:8081/realms/ifood
      publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwnxvfHnoKJCk7RvWKDwpcbJTkWl2NXux7j+gx8cJyV4y9R9dwBMAh+d6NCIe+752B5jpS2gZcU3YwahFS9An6UizGLmghC07WY3i9mrWCjVkmGaumIbgX7j+TUKi1NdGye5mvHeuLT2xvjn+gDZpxd7udSG1QaocXLs9B9CIauuWkRg35KheDJykLAILXk1xcURmU+i55E7xUOadg3b5Qxo8WbDY8MuNQ1GdHis7gv4BPB1l6wwSDwn3gCoRyVkMpKOrznzFv1vaOZcSGHsmCk3dGanfqvM61nNkhFqRRuP2NafHecYjCIDynTfShUqlR3A/doixXpW7QHafYvEPrwIDAQAB