quarkus:
  application:
    name: marketplace
  http:
    port: 8084
  devservices:
    enabled: false
  datasource:
    devservices:
      enabled: false
    db-kind: postgresql
    username: marketplace
    password: marketplace
    jdbc: false
    jdbc:
      url: jdbc:postgresql://localhost:5434/marketplace
    reactive:
      url: postgresql://localhost:5434/marketplace
  hibernate-orm:
    database:
      generation: update
  flyway:
    clean-at-start: true
    migrate-at-start: true
    
amqp-host: localhost
amqp-port: 5672
amqp-username: artemis
amqp-password: artemis

mp:
  messaging:
    incoming:
      restaurantes:
        connector: smallrye-amqp
        address: restaurantes
    outgoing:
      pedidos:
        connector: smallrye-kafka
        topic: pedidos
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
kafka:
  bootstrap:
    servers: localhost:9092