CREATE TABLE localizacao (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	latitude float8 NULL,
	longitude float8 NULL,
	CONSTRAINT localizacao_pkey PRIMARY KEY (id)
);

CREATE TABLE restaurante (
    id             int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome           varchar(50) NULL,
    cnpj           char(14)    NOT NULL,
    localizacao_id int8        NOT NULL,
    CONSTRAINT restaurante_pkey PRIMARY KEY (id)
);

ALTER TABLE restaurante ADD CONSTRAINT res_loc FOREIGN KEY (localizacao_id) REFERENCES localizacao(id);

CREATE TABLE prato (
    id             int8           NOT NULL,
    descricao      varchar(200)   NULL,
    nome           varchar(50)    NULL,
    preco          numeric(19, 2) NOT NULL,
    restaurante_id int8           NOT NULL,
    constraint PK_prato primary key (id)
);

ALTER TABLE prato ADD CONSTRAINT prato_rest FOREIGN KEY (restaurante_id) REFERENCES restaurante(id);

INSERT INTO localizacao (id, latitude, longitude)
VALUES (1000, -15.817759, -47.836959),
       (1001, -6.4768, 85.7464);

INSERT INTO restaurante (id, localizacao_id, nome, cnpj)
VALUES (111, 1000, 'Giassi', '73439430000188'),
       (222, 1001, 'Bom Burger', '92560415000138');

INSERT INTO prato
(id, nome, descricao, restaurante_id, preco)
VALUES(9998, 'Bife com fritas', 'Bom demais no almoço', 222, 23.99);

INSERT INTO prato
(id, nome, descricao, restaurante_id, preco)
VALUES(9997, 'Costela', 'Costela assada', 222, 149.99);