global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # Defina aqui os arquivos de regras se necessário
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ifood-cadastro"
    scrape_interval: 3s
    metrics_path: "/q/metrics"
    static_configs:
      - targets: ["host.docker.internal:8083"]